// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qQSYkYdOwtxNN1vRWRcQN7AuEBRyY8E',
    appId: '1:393949825596:android:cd2c064c085402a8175139',
    messagingSenderId: '393949825596',
    projectId: 'sushruta-lgs-19d1c',
    storageBucket: 'sushruta-lgs-19d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcgDd0b4xL8QX6QltGyAsGF7MM3Ka13VI',
    appId: '1:393949825596:ios:39236de7929c1bd8175139',
    messagingSenderId: '393949825596',
    projectId: 'sushruta-lgs-19d1c',
    storageBucket: 'sushruta-lgs-19d1c.firebasestorage.app',
    iosBundleId: 'com.sushruta.lgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcgDd0b4xL8QX6QltGyAsGF7MM3Ka13VI',
    appId: '1:393949825596:ios:5fa7a9432461ef80175139',
    messagingSenderId: '393949825596',
    projectId: 'sushruta-lgs-19d1c',
    storageBucket: 'sushruta-lgs-19d1c.firebasestorage.app',
    iosBundleId: 'com.example.shusrutaLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDchDDygL-c1jtBxsi99XF6CnJT2dzgxZA',
    appId: '1:393949825596:web:32205a40347f8c00175139',
    messagingSenderId: '393949825596',
    projectId: 'sushruta-lgs-19d1c',
    authDomain: 'sushruta-lgs-19d1c.firebaseapp.com',
    storageBucket: 'sushruta-lgs-19d1c.firebasestorage.app',
    measurementId: 'G-SKQE7H4XX0',
  );
}
